FROM maven:3.8.3-jdk-11-slim as builder

WORKDIR /app

COPY pom.xml ./
COPY src ./src
RUN mvn clean package -DskipTests

FROM adoptopenjdk/openjdk11:jre-11.0.15_10-alpine

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8000

CMD java $JAVA_OPTS -jar app.jar