FROM maven:3.8.6-openjdk-17 as builder

WORKDIR /project

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /project/src

RUN mvn package

FROM openjdk:17-jdk-slim

RUN mkdir /app

RUN addgroup -g 1001 -S tecogroup

RUN adduser -S teco -u 1001

COPY --from=build /project/target/llmspring-0.0.1-SNAPSHOT.jar /app/bmi.jar

WORKDIR /app

RUN chown -R teco:tecogroup /app

EXPOSE 8000

CMD java $JAVA_OPTS -jar bmi.jar